Repository PrefectHQ/prefect-operator, pull requests merged in 2024-09, with the labels that each got.

#58 Add GitHub workflow for releases
  .github/release.yaml
  .github/workflows/docker.yaml
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  .mise.toml
  .pre-commit-config.yaml
  .yamllint
Labels: maintenance

#65 Fix Docker image name for prod environment
  .github/workflows/release.yaml
Labels: maintenance

#67 Fix environment logic
  .github/workflows/release.yaml
Labels: maintenance

#68 Fix production docker image name
  .github/workflows/release.yaml
Labels: maintenance

#69 Align the default server name in the sample
  config/samples/v1_prefectworkpool_process.yaml
Labels: fix

#61 Support specifying which namespace(s) to watch
  cmd/main.go
  config/manager/manager.yaml
Labels: enhancement

#86 Add `batch job` permissions to operator
  deploy/charts/prefect-operator/templates/rbac.yaml
Labels: fix

#87 Package all manifests with release
  .github/workflows/helm-unittest.yaml
  .github/workflows/operator-lint-and-test.yaml
  .github/workflows/release.yaml
  .mise.toml
  .yamllint
  Makefile
  deploy/samples/kustomization.yaml
  deploy/samples/v1_prefectworkpool_external_prefect_cloud.yaml
Labels: maintenance
